version: 2.1
jobs:
  build-and-deploy:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Create maven settings
          command: echo $MVN_SETTINGS > .circleci/.settings.xml
      - run:
          name: Build and deploy
          command: mvn -s .circleci/.settings.xml clean package docker:build docker:push

workflows:
  test:
    jobs:
      - build-and-deploy